### ISSUE TITLE
Exception in thread "main" htsjdk.samtools.SAMException: Sequence name '<feff>rs1001834_A' doesn't match regex: '[0-9A-Za-z!#$%&+./:;?@^_|~-][0-9A-Za-z!#$%&*+./:;=?@^_|~-]*'

### ISSUE THREAD

**Issue by bioarpit1** [shendurelab/MPRAflow#18]
Hi I am trying to run MPRAflow on my small test dataset, (i can provide files if you want to test at your end).I am getting this error 

"14:22:47.144 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAflow/work/conda/mpraflow_py36-1978c54da7aacd41df3c7a4cb7639795/share/picard-2.20.8-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Jan 29 14:22:47 PST 2020] CreateSequenceDictionary OUTPUT=design_rmIllegalChars.fa.dict REFERENCE=design_rmIllegalChars.fa    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jan 29 14:22:47 PST 2020] Executing as arpitm@h001.grid.gs.washington.edu on Linux 2.6.32-696.30.1.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.8-SNAPSHOT
[Wed Jan 29 14:22:47 PST 2020] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=518979584
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Sequence name '<feff>rs1001834_A' doesn't match regex: '[0-9A-Za-z!#$%&+./:;?@^_|~-][0-9A-Za-z!#$%&*+./:;=?@^_|~-]*'
        at htsjdk.samtools.SAMSequenceRecord.validateSequenceName(SAMSequenceRecord.java:212)
        at htsjdk.samtools.SAMSequenceRecord.<init>(SAMSequenceRecord.java:95)
        at picard.util.SequenceDictionaryUtils$SamSequenceRecordsIterator.makeSequenceRecord(SequenceDictionaryUtils.java:107)
        at picard.util.SequenceDictionaryUtils$SamSequenceRecordsIterator.next(SequenceDictionaryUtils.java:136)
        at picard.util.SequenceDictionaryUtils$SamSequenceRecordsIterator.next(SequenceDictionaryUtils.java:57)
        at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:233)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)"

**Comment by makirc** [comment]
Hi there,

Looks like picard does not like the names of your reference sequences. You could try replacing underscores (_) by dashes (-) in your sequence identifiers. If I read the regular expression correctly, this should help. Let me know if that solved your problem.

Best,

Martin

**Comment by bioarpit1** [comment]
Hi Martin, Thanks for your suggestion, it resolved my problem

Thanks

Arpit
