### ISSUE TITLE
Error at Process `generate_mpranalyze_inputs (1)` stage 

### ISSUE THREAD

**Issue by Minb88** [shendurelab/MPRAflow#77]
Hello, 

This maybe an update issue as I have run the same data with no problems using MPRAflow earlier before having to re-download and update. I am currently using MPRAflow v2.3.5 and Nexflow v20.10.0. 

I am getting the following error when running with the MPRAnalyze option (and the final labelled output file in the directory is empty):
Error executing process > 'generate_mpranalyze_inputs (1)'

Caused by:
  Process `generate_mpranalyze_inputs (1)` terminated with an error exit status (1)

Command executed:

  python /vf/users/patelmb/MPRAflow_2/MPRAflow/src/mpranalyze_compiler.py null_final_labeled_counts.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/vf/users/patelmb/MPRAflow_2/MPRAflow/src/mpranalyze_compiler.py", line 82, in <module>
      parse(sys.argv[1])
    File "/vf/users/patelmb/MPRAflow_2/MPRAflow/src/mpranalyze_compiler.py", line 39, in parse
      n_bc = max([len(x) for x in rna_dict.values()])
  ValueError: max() arg is an empty sequence

Work dir:
  /vf/users/patelmb/MPRAflow_2/MPRAflow/work/10/c500b6364bbf7332246a665e648036

Appreciate any help. 

Best,
Min

**Comment by iris-chin** [comment]
Hi Min,

I have just run into the same error. Were you able to determine what was causing this issue for you?

Best,
Iris

**Comment by llxts** [comment]
Hi both, 

not sure if yall are still having issues with this. I got the same error previously and it was due to the txt input (i.e. null_final_labeled_counts.txt) not having any data apart from the header. 

I edited the file 'label_final_count_mat.py', and changed 15 to the length of my Barcode, and it worked out for me. 
`mask=(counts['Barcode'].str.len() == 15)`
